repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace  # Remove trailing whitespace
      - id: end-of-file-fixer     # Ensure files end with newline
      - id: check-yaml            # Validate YAML syntax
      - id: check-added-large-files  # Prevent large files (>500KB)
        args: [--maxkb=500]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black                # Auto-format Python code
        language_version: python3.8

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort                # Sort Python imports
        name: isort (python)
        args: [--profile, black]  # Black-compatible settings

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8               # Lint Python code
        additional_dependencies: [flake8-bugbear]
        args: [
          --max-line-length=127,
          --max-complexity=10,
          --ignore=E203,W503
        ]

  # Additional useful hooks
  - repo: https://github.com/pycqa/mypy
    rev: v0.971
    hooks:
      - id: mypy                # Static type checking
        args: [--ignore-missing-imports]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier            # Format non-Python files
        args: [--prose-wrap, always]
        types: [markdown, yaml, json, html]