name: crypto-trading-ai
channels:
  - conda-forge
dependencies:
  - python=3.10   # better supported than 3.8 on Apple Silicon
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - requests
  - flask
  - pytest
  - pyyaml
  - plotly
  - statsmodels
  - ta-lib
  - ipykernel
  - pip
  - pip:
      - tensorflow-macos
      - tensorflow-metal   # GPU acceleration for M1/M2/M3 chips
      - keras
      - dash
      - dash-bootstrap-components
      - gunicorn
      - python-binance