# default.yaml

project:
  name: "Crypto Trading AI Research"
  description: "This project aims to implement AI techniques for crypto trading, focusing on data analysis, feature engineering, model training, and backtesting strategies."

data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  external_data_path: "data/external"

  data_source:
    api_url: "https://api.coingecko.com/api/v3" # Example API
    coin: "bitcoin"
    currency: "usd"
    days: 365

notebooks:
  exploration_notebook: "notebooks/01-data-exploration.ipynb"
  feature_engineering_notebook: "notebooks/02-feature-engineering.ipynb"
  model_prototyping_notebook: "notebooks/03-model-prototyping.ipynb"

scripts:
  fetch_data_script: "scripts/fetch_data.py"
  run_experiment_script: "scripts/run_experiment.sh"
  evaluate_script: "scripts/evaluate.sh"

experiments:
  results_path: "experiments/experiment_YYYY-MM-DD_id/results.csv"
  config_path: "experiments/experiment_YYYY-MM-DD_id/config.yaml"

models:
  checkpoints_path: "models/checkpoints"

testing:
  test_data_path: "tests/test_data.py"
  test_models_path: "tests/test_models.py"

documentation:
  project_plan: "docs/project_plan.md"
  experiments_doc: "docs/experiments.md"
  reproducibility_doc: "docs/reproducibility.md"

status:
  objectives_defined: true
  data_collected: false
  data_explored: false
  data_preprocessed: false
  features_engineered: false
  models_prototyped: false
  backtesting_completed: false
  experiments_tracked: false
  evaluation_done: false
  api_developed: false
  documentation_updated: false
  testing_completed: false
  final_reviewed: false